root: ./

structure:
  readme: ./README.md
  summary: ./SUMMARY.md

redirects:
  develop/public-endpoints: nodes/public-endpoints.md
  getting-started: README.md
  getting-started/wallet: defi/wallet/README.md
  getting-started/wallet/create-a-wallet: defi/wallet/create.md
  getting-started/wallet/accounts: defi/wallet/accounts.md
  getting-started/wallet/staking: defi/wallet/staking.md
  getting-started/wallet/governance: defi/wallet/governance.md
  getting-started/wallet/auction: defi/wallet/auction.md
  guides/bridge: defi/bridge/README.md
  getting-started/token-standards: defi/tokens/README.md
  getting-started/token-standards/inj-coin: defi/tokens/inj-coin.md
  getting-started/token-standards/token-factory: defi/tokens/token-factory.md
  getting-started/token-standards/cw20-standard: defi/tokens/cw20-standard.md
  getting-started/transactions: defi/transactions.md
  getting-started/transactions/gas-and-fees: defi/transaction-fees.md
  nodes/getting-started/interact-with-a-node: infra/interact-node-rest.md
  nodes/getting-started/running-a-node: infra/run-node.md
  nodes/getting-started/running-a-node/1.-setting-up-the-keyring: infra/set-up-keyring.md
  nodes/getting-started/running-a-node/join-a-network: infra/join-a-network.md
  nodes/getting-started/running-a-node/cosmovisor: infra/cosmovisor.md
  nodes/getting-started/running-a-node/upgrade-your-node: infra/upgrade-node.md
  nodes/validators: infra/validator-mainnet/README.md
  nodes/validators/mainnet: infra/validator-mainnet/README.md
  nodes/validators/mainnet/peggo: infra/validator-mainnet/peggo.md
  nodes/validators/mainnet/canonical-chain-upgrades: infra/validator-mainnet/canonical-chain-upgrade.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-10002-rc1: infra/validator-mainnet/canonical-chain-upgrade-10002-rc1.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-10002-rc2: infra/validator-mainnet/canonical-chain-upgrade-10002-rc2.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-10003-rc1: infra/validator-mainnet/canonical-chain-upgrade-10003-rc1.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-10004-rc1: infra/validator-mainnet/canonical-chain-upgrade-10004-rc1.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-10004-rc1-patch: infra/validator-mainnet/canonical-chain-upgrade-10004-rc1-patch.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-10005-rc1: infra/validator-mainnet/canonical-chain-upgrade-10005-rc1.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-10006-rc1: infra/validator-mainnet/canonical-chain-upgrade-10006-rc1.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-10007-rc1: infra/validator-mainnet/canonical-chain-upgrade-10007-rc1.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-10008: infra/validator-mainnet/canonical-chain-upgrade-10008.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-10009: infra/validator-mainnet/canonical-chain-upgrade-10009.md
  nodes/validators/mainnet/canonical-chain-upgrades/upgrade-to-v1.10: infra/validator-mainnet/canonical-chain-upgrade-v1.10.0.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-10011: infra/validator-mainnet/canonical-chain-upgrade-v1.11.0.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-1-12: infra/validator-mainnet/canonical-chain-upgrade-v1.12.0.md
  nodes/validators/mainnet/canonical-chain-upgrades/upgrade-to-v1.12.1: infra/validator-mainnet/canonical-chain-upgrade-v1.12.1.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-1.13.0: infra/validator-mainnet/canonical-chain-upgrade-1.13.0.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-1.13.2: infra/validator-mainnet/canonical-chain-upgrade-1.13.2.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-1.13.3: infra/validator-mainnet/canonical-chain-upgrade-1.13.3.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-1.14.0: infra/validator-mainnet/canonical-chain-upgrade-1.14.0.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-1.14.1: infra/validator-mainnet/canonical-chain-upgrade-1.14.1.md
  nodes/validators/mainnet/canonical-chain-upgrades/canonical-1.15.0: infra/validator-mainnet/canonical-chain-upgrade-1.15.0.md
  nodes/validators/testnet: infra/validator-testnet/README.md
  nodes/validators/testnet/testnet-peggo: infra/validator-testnet/peggo.md
  nodes/validators/cosmosvisor: infra/cosmovisor.md
  nodes/public-endpoints: infra/public-endpoints.md
  nodes/private-nodes: infra/premium-endpoints.md
  developers/modules: developers-native/README.md
  developers/modules/injective: developers-native/injective/README.md
  developers/modules/injective/auction: developers-native/injective/auction/README.md
  developers/modules/injective/auction/01_state: developers-native/injective/auction/01_state.md
  developers/modules/injective/auction/02_messages: developers-native/injective/auction/02_messages.md
  developers/modules/injective/auction/03_end_block: developers-native/injective/auction/03_end_block.md
  developers/modules/injective/auction/04_events: developers-native/injective/auction/04_events.md
  developers/modules/injective/auction/05_params: developers-native/injective/auction/05_params.md
  developers/modules/injective/auction/99_errors: developers-native/injective/auction/99_errors.md
  developers/modules/injective/exchange: developers-native/injective/exchange/README.md
  developers/modules/injective/exchange/00_derivative_market_concepts: developers-native/injective/exchange/00_derivative_market_concepts.md
  developers/modules/injective/exchange/01_spot_market_concepts: developers-native/injective/exchange/01_spot_market_concepts.md
  developers/modules/injective/exchange/02_binary_options_markets: developers-native/injective/exchange/02_binary_options_markets.md
  developers/modules/injective/exchange/02_other_concepts: developers-native/injective/exchange/02_other_concepts.md
  developers/modules/injective/exchange/03_state: developers-native/injective/exchange/03_state.md
  developers/modules/injective/exchange/04_state_transitions: developers-native/injective/exchange/04_state_transitions.md
  developers/modules/injective/exchange/05_messages: developers-native/injective/exchange/05_messages.md
  developers/modules/injective/exchange/06_proposals: developers-native/injective/exchange/06_proposals.md
  developers/modules/injective/exchange/07_begin_block: developers-native/injective/exchange/07_begin_block.md
  developers/modules/injective/exchange/08_end_block: developers-native/injective/exchange/08_end_block.md
  developers/modules/injective/exchange/09_events: developers-native/injective/exchange/09_events.md
  developers/modules/injective/exchange/10_params: developers-native/injective/exchange/10_params.md
  developers/modules/injective/exchange/11_msg_privileged_execute_contract: developers-native/injective/exchange/11_msg_privileged_execute_contract.md
  developers/modules/injective/exchange/99_errors: developers-native/injective/exchange/99_errors.md
  developers/modules/injective/insurance: developers-native/injective/insurance/README.md
  developers/modules/injective/insurance/01_state: developers-native/injective/insurance/01_state.md
  developers/modules/injective/insurance/02_state_transitions: developers-native/injective/insurance/02_state_transitions.md
  developers/modules/injective/insurance/03_messages: developers-native/injective/insurance/03_messages.md
  developers/modules/injective/insurance/04_end_block: developers-native/injective/insurance/04_end_block.md
  developers/modules/injective/insurance/05_events: developers-native/injective/insurance/05_events.md
  developers/modules/injective/insurance/06_params: developers-native/injective/insurance/06_params.md
  developers/modules/injective/insurance/07_future_improvements: developers-native/injective/insurance/07_future_improvements.md
  developers/modules/injective/insurance/99_errors: developers-native/injective/insurance/99_errors.md
  developers/modules/injective/ocr: developers-native/injective/ocr/README.md
  developers/modules/injective/ocr/01_concepts: developers-native/injective/ocr/01_concepts.md
  developers/modules/injective/ocr/02_state: developers-native/injective/ocr/02_state.md
  developers/modules/injective/ocr/03_messages: developers-native/injective/ocr/03_messages.md
  developers/modules/injective/ocr/04_proposals: developers-native/injective/ocr/04_proposals.md
  developers/modules/injective/ocr/05_begin_block: developers-native/injective/ocr/05_begin_block.md
  developers/modules/injective/ocr/06_hooks: developers-native/injective/ocr/06_hooks.md
  developers/modules/injective/ocr/07_events: developers-native/injective/ocr/07_events.md
  developers/modules/injective/ocr/08_params: developers-native/injective/ocr/08_params.md
  developers/modules/injective/ocr/99_errors: developers-native/injective/ocr/99_errors.md
  developers/modules/injective/oracle: developers-native/injective/oracle/README.md
  developers/modules/injective/oracle/01_state: developers-native/injective/oracle/01_state.md
  developers/modules/injective/oracle/02_keeper: developers-native/injective/oracle/02_keeper.md
  developers/modules/injective/oracle/03_messages: developers-native/injective/oracle/03_messages.md
  developers/modules/injective/oracle/04_proposals: developers-native/injective/oracle/04_proposals.md
  developers/modules/injective/oracle/05_events: developers-native/injective/oracle/05_events.md
  developers/modules/injective/oracle/06_future_improvements: developers-native/injective/oracle/06_future_improvements.md
  developers/modules/injective/oracle/99_errors: developers-native/injective/oracle/99_errors.md
  developers/modules/injective/peggy: developers-native/injective/peggy/README.md
  developers/modules/injective/peggy/01_definitions: developers-native/injective/peggy/01_definitions.md
  developers/modules/injective/peggy/02_workflow: developers-native/injective/peggy/02_workflow.md
  developers/modules/injective/peggy/03_state: developers-native/injective/peggy/03_state.md
  developers/modules/injective/peggy/04_messages: developers-native/injective/peggy/04_messages.md
  developers/modules/injective/peggy/05_slashing: developers-native/injective/peggy/05_slashing.md
  developers/modules/injective/peggy/06_end_block: developers-native/injective/peggy/06_end_block.md
  developers/modules/injective/peggy/07_events: developers-native/injective/peggy/07_events.md
  developers/modules/injective/peggy/08_params: developers-native/injective/peggy/08_params.md
  developers/modules/injective/peggy/09_relay_semantics: developers-native/injective/peggy/09_relay_semantics.md
  developers/modules/injective/peggy/10_future_improvements: developers-native/injective/peggy/10_future_improvements.md
  developers/modules/injective/peggy/99_errors: developers-native/injective/peggy/99_errors.md
  developers/modules/injective/permissions: developers-native/injective/permissions/README.md
  developers/modules/injective/permissions/01_concepts: developers-native/injective/permissions/01_concepts.md
  developers/modules/injective/permissions/02_state: developers-native/injective/permissions/02_state.md
  developers/modules/injective/permissions/03_state_transitions: developers-native/injective/permissions/03_state_transitions.md
  developers/modules/injective/permissions/99_errors: developers-native/injective/permissions/99_errors.md
  developers/modules/injective/tokenfactory: developers-native/injective/tokenfactory/README.md
  developers/modules/injective/tokenfactory/01_concepts: developers-native/injective/tokenfactory/01_concepts.md
  developers/modules/injective/tokenfactory/02_state: developers-native/injective/tokenfactory/02_state.md
  developers/modules/injective/tokenfactory/03_messages: developers-native/injective/tokenfactory/03_messages.md
  developers/modules/injective/tokenfactory/04_events: developers-native/injective/tokenfactory/04_events.md
  developers/modules/injective/tokenfactory/05_params: developers-native/injective/tokenfactory/05_params.md
  developers/modules/injective/tokenfactory/99_errors: developers-native/injective/tokenfactory/99_errors.md
  developers/modules/injective/wasmx: developers-native/injective/wasmx/README.md
  developers/modules/injective/wasmx/01_concepts: developers-native/injective/wasmx/01_concepts.md
  developers/modules/injective/wasmx/02_data: developers-native/injective/wasmx/02_data.md
  developers/modules/injective/wasmx/03_proposals: developers-native/injective/wasmx/03_proposals.md
  developers/modules/injective/wasmx/04_messages: developers-native/injective/wasmx/04_messages.md
  developers/modules/injective/wasmx/05_params: developers-native/injective/wasmx/05_params.md
  developers/modules/injective/wasmx/99_errors: developers-native/injective/wasmx/99_errors.md
  developers/modules/injective/lanes: developers-native/injective/lanes/README.md
  developers/modules/injective/txfees: developers-native/injective/txfees/README.md
  developers/modules/core: developers-native/core/README.md
  developers/modules/core/auth: developers-native/core/auth/README.md
  developers/modules/core/authz: developers-native/core/authz/README.md
  developers/modules/core/bank: developers-native/core/bank/README.md
  developers/modules/core/consensus: developers-native/core/consensus/README.md
  developers/modules/core/crisis: developers-native/core/crisis/README.md
  developers/modules/core/distribution: developers-native/core/distribution/README.md
  developers/modules/core/evidence: developers-native/core/evidence/README.md
  developers/modules/core/feegrant: developers-native/core/feegrant/README.md
  developers/modules/core/gov: developers-native/core/gov/README.md
  developers/modules/core/group: developers-native/core/group/README.md
  developers/modules/core/mint: developers-native/core/mint/README.md
  developers/modules/core/nft: developers-native/core/nft/README.md
  developers/modules/core/params: developers-native/core/params/README.md
  developers/modules/core/slashing: developers-native/core/slashing/README.md
  developers/modules/core/staking: developers-native/core/staking/README.md
  developers/modules/core/upgrade: developers-native/core/upgrade/README.md
  developers/modules/core/circuit: developers-native/core/circuit/README.md
  developers/modules/core/genutils: developers-native/core/genutils.md
  developers/exchange-developers: developers-defi/README.md
  developers-defi/wallet: defi/wallet/README.md
  developers-defi/tokens: defi/tokens/README.md
  guides/launch-a-token: developers-defi/token-launch.md
  guides/launch-a-market: developers-defi/market-launch.md
  guides/denom-metadata: developers-defi/denom-and-bank.md
  developers/exchange-developers/provider-oracle: developers-defi/provider-oracle.md
